views/blueprints/user/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import logout_user, login_user, login_required, current_user

from ...forms import *
from login_and_model import db, User, Order
from app import bcrypt

user = Blueprint("user", __name__)


@user.route("/reg", methods=["GET", "POST"])
def registration_page():
    form = RegForm()
    if request.method == "POST":
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(name=form.name.data, surname=form.surname.data,
                    email=form.email.data, phone_number=form.phone_number.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account is created")
        return redirect(url_for("user.login"))

    return render_template("user/reg.html", form=form)


@user.route("/log", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        user = User.query.filter(User.email == form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("general.general_page"))
        else:
            flash("Login Unsuccessful.Pleas check your email or password")

    return render_template("user/login.html", form=form)


@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect("/")


@user.route("/account/<int:id>")
def detail_user(id):
    if current_user.id != id:
        return render_template("error/404.html")
    orders = Order.query.filter(Order.user_id == id).all()
    return render_template("user/detail.html", orders=orders)


@user.route("/order")
@login_required
def manager_page():
    if current_user.role_id != 2:
        return render_template("error/404.html")
    orders = Order.query.all()
    return render_template("user/manage.html", orders=orders)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
            crossorigin="anonymous"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for("general.general_page") }}">ObstShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if current_user.role_id == 3 %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">admin</a>
                    </li>
                {% elif current_user.role_id == 2 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("user.manager_page") }}">order</a>
                    </li>
                {% else %}
                    {% if current_user.role_id == 1 %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("user.detail_user", id=current_user.id) }}">account</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("user.login") }}">account</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('user.logout') }}" class="nav-item nav-link">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('user.login') }}" class="nav-item nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('user.registration_page') }}" class="nav-item nav-link">Registration</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" style="margin: 10px">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
{% block content %}
{% endblock %}
</body>
</html>