views/blueprints/item/routes.py
from flask import Blueprint, render_template, \
    redirect, request, url_for, flash
from flask_login import current_user, login_required
from login_and_model import db, Item, City, Delivery, Payment, Order

from ...forms import OrderForm, UpdateOrder
from .task import get_order, get_status

item = Blueprint("item", __name__)


@item.route("/<string:name>", methods=["GET", "POST"])
def item_detail(name):
    item = Item.query.filter(Item.item_name == name).first()
    return render_template("item/detail.html", item=item)


@item.route("/order/<string:name>", methods=["GET", "POST"])
def order_item(name):
    item = Item.query.filter(Item.item_name == name).first()
    form = OrderForm()

    if request.method == "POST":
        order_info = {"id": current_user.id, "phone": form.phone.data,
                      "item": item.item_name, "city": form.city.data, "delivery_type": form.delivery.data,
                      "payment": form.payment.data, "comments": form.comments.data, "price": item.price}
        get_order.delay(order_info)
        flash("Your order has been create!", "success")
        return redirect(url_for("general.general_page"))

    if current_user.is_authenticated:
        form.name.data = current_user.name
        form.surname.data = current_user.surname
        form.phone.data = current_user.phone_number

    form.city.choices = [city.city_name for city in City.query.all()]
    form.delivery.choices = [delivery.delivery_type for delivery in Delivery.query.all()]
    form.payment.choices = [payment.method for payment in Payment.query.all()]

    return render_template("item/order.html", form=form, item=item)


@item.route("/<int:id>", methods=["GET", "POST"])
@login_required
def detail_order(id):
    order = Order.query.filter(Order.id == id).first()
    form = UpdateOrder()

    if request.method == "POST":
        get_status.delay({"status": form.status.data, "id": id})

        db.session.commit()
        return redirect(url_for("user.manager_page"))

    if current_user.role_id == 2:
        return render_template("item/order_detail.html", order=order, form=form)
    elif current_user.id != order.user_id and current_user.role_id != 2:
        return render_template('error/404.html')
    return render_template("item/order_detail.html", order=order)

templates/item/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ item.item_name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12" style="margin-top: 20px;margin-bottom: 15px">
                <h2>
                    {{ item.item_name }}
                </h2>
            </div>
            <div class="col-md-12">
                <figure class="figure">
                    <img src="{{ item.img }}" class="figure-img img-fluid rounded" alt="{{ item.name }}">
                </figure>
                <div align="justify" class="col-md-6" style="margin-top: 20px">
                    <p class="text-start">{{ item.description }}</p>
                </div>
            </div>
            <div class="col-md-4" style="margin-bottom: 40px">
                <div class="btn">
                        <a href="{{ url_for("item.order_item", name=item.item_name) }}" class="btn btn-primary">Kaufen</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/item/order.html
{% extends 'base.html' %}

{% block title %}
    order
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>
                    Befehl {{ item.item_name }}
                </h2>
            </div>
            <div class="col-md-8">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Kundenname
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="form-group">
                                        {{ form.name.label(class="form-control-label") }}
                                        {% if form.name.errors %}
                                            {{ form.name(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.name.errors %}
                                                    <spen>{{ error }}</spen>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.name(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {{ form.surname.label(class="form-control-label") }}
                                        {% if form.surname.errors %}
                                            {{ form.surname(class="form-control form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.surname.errors %}
                                                    <spen>{{ error }}</spen>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.surname(class="form-control form-control-lg") }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Stadt und ,Zahlungsart Versandart
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="form-group">
                                        {{ form.city.label(class="form-control-label") }}
                                        {% if form.city.errors %}
                                            {{ form.city(class="form-select form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.city.errors %}
                                                    <spen>{{ error }}</spen>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.city(class="form-select form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {{ form.payment.label(class="form-control-label") }}
                                        {% if form.payment.errors %}
                                            {{ form.payment(class="form-select form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.payment.errors %}
                                                    <spen>{{ error }}</spen>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.payment(class="form-select form-control-lg") }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {{ form.delivery.label(class="form-control-label") }}
                                        {% if form.delivery.errors %}
                                            {{ form.delivery(class="form-select form-control-lg is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.delivery.errors %}
                                                    <spen>{{ error }}</spen>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.delivery(class="form-select form-control-lg") }}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingThree">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseThree" aria-expanded="false"
                                    aria-controls="collapseThree">
                                Handynummer und Kommentar
                            </button>
                        </h2>
                        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                             data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="form-group">
                                    {{ form.phone.label(class="form-control-label") }}
                                    {% if form.phone.errors %}
                                        {{ form.phone(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.phone.errors %}
                                                <spen>{{ error }}</spen>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.phone(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.comments.label(class="form-control-label") }}
                                    {% if form.comments.errors %}
                                        {{ form.comments(class="form-control form-control-lg is-invalid") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.comments.errors %}
                                                <spen>{{ error }}</spen>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.comments(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 20px">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/item/order_detail.html
{% extends 'base.html' %}

{% block title %}
    Order
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="display-4">
                    {{ order.item }}
                </h2>
            </div>
            <div class="col-md-8">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ order.comments }}</li>
                    <li class="list-group-item">{{ order.delivery_type }}</li>
                    <li class="list-group-item">{{ order.order_city }}</li>
                    <li class="list-group-item"><h5>{{ order.price }} €</h5></li>
                </ul>
            </div>
            <div class="col-12">
                {% if current_user.role_id == 2 %}
                    <div class="conten-section" style="margin: 30px">
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Join Today</legend>
                            <div class="form-group">
                                {{ form.status.label(class="form-control-label") }}

                                {% if form.status.errors %}
                                    {{ form.status(class="form-select form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.status.errors %}
                                            <spen>{{ error }}</spen>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.status(class="form-select form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group" style="margin: 20px">
                                {{ form.submit(class="btn btn-outline-info") }}
                            </div>
                    </form>
                {% else %}
                    {% if order.status == False %}
                        <h4 class="display-6" style="color: #ffc107">
                            nicht Schaffen
                        </h4>
                    {% else %}
                        <h4 class="display-6" style="color: #198754">
                            Schaffen
                        </h4>
                    {% endif %}
                {% endif %}
                </div>
            </div>
        </div>
{% endblock %}