login_and_model/login/__init__.py
from .login import login

views/blueprints/item/routes.py
from flask import Blueprint, render_template, \
    redirect, request, url_for, flash
from flask_login import current_user, login_required
from login_and_model import db, Item, City, Delivery, Payment, Order

from ...forms import OrderForm, UpdateOrder
from .task import get_order, get_status

item = Blueprint("item", __name__)


@item.route("/<string:name>", methods=["GET", "POST"])
def item_detail(name):
    item = Item.query.filter(Item.item_name == name).first()
    return render_template("item/detail.html", item=item)


@item.route("/order/<string:name>", methods=["GET", "POST"])
def order_item(name):
    item = Item.query.filter(Item.item_name == name).first()
    form = OrderForm()

    if request.method == "POST":
        order_info = {"id": current_user.id, "phone": form.phone.data,
                      "item": item.item_name, "city": form.city.data, "delivery_type": form.delivery.data,
                      "payment": form.payment.data, "comments": form.comments.data, "price": item.price}
        get_order.delay(order_info)
        flash("Your order has been create!", "success")
        return redirect(url_for("general.general_page"))

    if current_user.is_authenticated:
        form.name.data = current_user.name
        form.surname.data = current_user.surname
        form.phone.data = current_user.phone_number

    form.city.choices = [city.city_name for city in City.query.all()]
    form.delivery.choices = [delivery.delivery_type for delivery in Delivery.query.all()]
    form.payment.choices = [payment.method for payment in Payment.query.all()]

    return render_template("item/order.html", form=form, item=item)


@item.route("/<int:id>", methods=["GET", "POST"])
@login_required
def detail_order(id):
    order = Order.query.filter(Order.id == id).first()
    form = UpdateOrder()

    if request.method == "POST":
        get_status.delay({"status": form.status.data, "id": id})

        db.session.commit()
        return redirect(url_for("user.manager_page"))

    if current_user.role_id == 2:
        return render_template("item/order_detail.html", order=order, form=form)
    elif current_user.id != order.user_id and current_user.role_id != 2:
        return render_template('error/404.html')
    return render_template("item/order_detail.html", order=order)

views/blueprints/user/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import logout_user, login_user, login_required, current_user

from ...forms import *
from login_and_model import db, User, Order
from app import bcrypt

user = Blueprint("user", __name__)


@user.route("/reg", methods=["GET", "POST"])
def registration_page():
    form = RegForm()
    if request.method == "POST":
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(name=form.name.data, surname=form.surname.data,
                    email=form.email.data, phone_number=form.phone_number.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account is created")
        return redirect(url_for("user.login"))

    return render_template("user/reg.html", form=form)


@user.route("/log", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        user = User.query.filter(User.email == form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("general.general_page"))
        else:
            flash("Login Unsuccessful.Pleas check your email or password")

    return render_template("user/login.html", form=form)


@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect("/")


@user.route("/account/<int:id>")
def detail_user(id):
    if current_user.id != id:
        return render_template("error/404.html")
    orders = Order.query.filter(Order.user_id == id).all()
    return render_template("user/detail.html", orders=orders)


@user.route("/order")
@login_required
def manager_page():
    if current_user.role_id != 2:
        return render_template("error/404.html")
    orders = Order.query.all()
    return render_template("user/manage.html", orders=orders)

templates/user/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ current_user.name }}
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12" style="margin-top: 20px;margin-bottom: 10px;">
                <h2>
                    {{ current_user.name }} {{ current_user.surname }}
                </h2>
            </div>
            <div class="col-md-8">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ current_user.email }}</li>
                    <li class="list-group-item">{{ current_user.phone_number }}</li>
                </ul>
            </div>
            <div class="col-12">
                <h3>
                    ihre Bestellung
                </h3>
            </div>
            <div class="col-md-8">
                {% for order in orders %}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{{ url_for("item.detail_order", id=order.id) }}" class="nav-link">
                                {{ order.item }}
                            </a>
                        </li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block titile %}
    Login
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h2>
                    Login
                </h2>
            </div>
            <div class="col-md-6">
                <div class="conten-section" style="margin: 30px">
                    <form method="POST">
                        {{ form.hidden_tag() }}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Join Today</legend>
                            <div class="form-group">
                                {{ form.email.label(class="form-control-label") }}

                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <spen>{{ error }}</spen>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ form.password.label(class="form-control-label") }}

                                {% if form.password.errors %}
                                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <spen>{{ error }}</spen>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </fieldset>

                        <div class="form-check" style="margin-top: 10px">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                        <div class="form-group" style="margin: 20px">
                            {{ form.submit(class="btn btn-outline-info") }}
                        </div>
                        <small class="text-muted">
                            <a href="#" class="ml-2" style="text-decoration: none;">Forgot Password?</a>
                        </small>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Need an Account? <a href="{{ url_for('users.registration_page') }}" class="ml-2"
                                                style="text-decoration: none">Sign Up Now</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/manage.html
{% extends 'base.html' %}

{% block title %}
    Orders
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>
                    Orders
                </h2>
            </div>
            <div class="col-md-8">
                {% for order in orders %}
                    <ul class="list-group list-group-flush">
                        {% if order.status %}
                            <li class="list-group-item">
                                <a href="{{ url_for("item.detail_order", id=order.id) }}" class="nav-link" style="color: #198754">{{ order }}</a>
                            </li>
                        {% else%}
                            <li class="list-group-item">
                                <a href="{{ url_for("item.detail_order", id=order.id) }}" class="nav-link" style="color: #ffc107">{{ order }}</a>
                            </li>
                        {% endif %}
                    </ul>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/reg.html
{% extends 'base.html' %}

{% block title %}
    registration
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>
                    Registration
                </h2>
            </div>
            <div class="col-md-4">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Join Today</legend>
                        <div class="form-group">
                            {{ form.name.label(class="form-control-label") }}
                            {% if form.name.errors %}
                                {{ form.name(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.name(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.surname.label(class="form-control-label") }}
                            {% if form.surname.errors %}
                                {{ form.surname(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.surname.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.surname(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.phone_number.label(class="form-control-label") }}

                            {% if form.phone_number.errors %}
                                {{ form.phone_number(class="form-control form-control-lg is-invalid", type="tel") }}
                                <div class="invalid-feedback">
                                    {% for error in form.phone_number.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.phone_number(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}

                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}

                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.confirm_password.label(class="form-control-label") }}

                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm_password.errors %}
                                        <spen>{{ error }}</spen>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group" style="margin: 20px">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Alredy Have an Account? <a href="#" class="ml-2">Sign In</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}